from src.2_design_contract.models.contract import HardwareSpecificationContract


def generate_sva_bind_file(contract: HardwareSpecificationContract) -> str:
    """Generates a standalone, synthesizable SystemVerilog Assertion (SVA) bind module."""
    clk_name = next((p.name for p in contract.ports if "clk" in p.name.lower()), "clk")
    rst_name = next((p.name for p in contract.ports if "rst" in p.name.lower()), "rst_n")

    rst_expr = f"!{rst_name}" if "low" in contract.reset_type else rst_name

    lines = [
        "// ============================================================================",
        f"// SystemVerilog Assertion (SVA) Formal Bind Module: {contract.module_name}_sva",
        "// Generated by PragyanAI-SpecForge",
        "// ============================================================================\n",
        "`timescale 1ns / 1ps\n",
        f"module {contract.module_name}_sva (",
    ]

    port_decls = []
    for p in contract.ports:
        port_decls.append(f"  input wire {p.width:<10} {p.name}")
    lines.append(",\n".join(port_decls))
    lines.append(");\n")
    lines.append(f"  default clocking cb_clk @(posedge {clk_name}); endclocking;")
    lines.append(f"  default disable iff ({rst_expr});\n")

    for cc in contract.corner_cases:
        lines.append(f"  // Scenario {cc.scenario_id}: {cc.title}")
        lines.append(f"  // Hazard: {cc.hazard_description}")
        lines.append(f"  {cc.sva_property}\n")

    lines.append("endmodule\n")

    port_binds = ", ".join([f".{p.name}({p.name})" for p in contract.ports])
    lines.append(f"// bind {contract.module_name} {contract.module_name}_sva inst_{contract.module_name}_sva ({port_binds});\n")

    return "\n".join(lines)
